version: "3.8"
services:
  kvstore:
    build:
      context: .
      dockerfile: kvstore/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ID=node-1
